# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Title
tagline:          The Tom Ray
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Tom Ray
  url:            https://twitter.com/lorenzosmusic
  email:          info@lorenzosmusic.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
